[package]
name = "football_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ratatui = "0.24.0"
crossterm = "0.27.0"
rand = "0.8.5"
argh = "0.1.12"
xml-rs = "0.8.19"